### PR TITLE
Drop dependencies on `querystring` and `url`

### PR DESCRIPTION
**Pull request by ryota-ka**
This pull request drops dependencies on Node.js's built-in `querystring` and `url` modules, by switching them to WHATWG's `URLSearchParams` and `URL` APIs internally, which are standardized and widely accepted.

It should also be noted that this pull request makes this library to be available not only on Node.js but also **on the Web out of the box** (namely, without polyfills).

---

Node.js's `url` module [has been deprecated since v11.0.0, and it is encouraged to use the WHATWG `URL` API instead](https://nodejs.org/docs/v11.0.0/api/url.html#url_legacy_url_api).
What is worse, the documentation for `url.parse()` of the latest version of Node.js [points out that it may introduce a security issue](https://nodejs.org/docs/v16.6.0/api/url.html#url_url_parse_urlstring_parsequerystring_slashesdenotehost).

> Because the `url.parse()` method uses a lenient, non-standard algorithm for parsing URL strings, security issues can be introduced. 

---

The same applies for `querystring` module. It is also [marked as "legacy" (stability: 3) since v14.17.1, and it is recommended to use WHATWG `URLSearchParams` API instead.](https://nodejs.org/docs/v14.17.1/api/querystring.html#querystring_query_string)

---

The API of the library remains unchanged, however this can potentially introduce breaking changes for some pathological inputs.

### CODE REVIEW

**Comment by ryota-ka** [comment]
This might resolve #58 and #60.

**Comment by ryota-ka** [comment]
Hi @gcanti, could you help me reviewing this? Thanks!

**Comment by jkomyno** [comment]
Hi @gcanti, by any chance, do you have any update on this PR?

**Comment by kalda341** [comment]
@ryota-ka I just implemented exactly this (in pretty much exactly the same way) before seeing this. I'd really like to get this merged.

I can't seem to run the tests though:
../../src/index.ts(30,39): error TS2304: Cannot find name 'URLSearchParams'.
../../src/index.ts(33,27): error TS7006: Parameter 'v' implicitly has an 'any' type.
../../src/index.ts(33,30): error TS7006: Parameter 'k' implicitly has an 'any' type.
../../src/index.ts(46,38): error TS2304: Cannot find name 'URLSearchParams'.
../../src/index.ts(47,30): error TS2304: Cannot find name 'URLSearchParams'.
../../src/index.ts(87,44): error TS2304: Cannot find name 'URL'.```
```

Any idea how to resolve this?

**Comment by kalda341** [comment]
As a short term solution I've published `@rico-technologies/fp-ts-routing-fork`.

For context, we needed this change as we couldn't migrate to pnpm without breaking our Vite build. This turned out to be the culprit.

**Comment by ryota-ka** [comment]
Hi @kalda341, sorry for the delayed reply.
Hmm, looks weird. It correctly typechecks when I run `$ npx tsc --noEmit --watch` locally.

Is the correct version of TypeScript referenced by your project?
`URL` and `URLSearchParams` should be defined in `lib.dom.d.ts`.

**Comment by kalda341** [comment]
@ryota-ka You're correct, it seems to work fine. I must have accidentally been running a weirdly set up global Typescript install?

@gcanti It would be great if we could get this merged! I'm currently running this in production without any issues.

**Comment by StefanoMagrassi** [comment]
superseded by #70

**Pull request closed without merging**
