### PR TITLE
add 'succeed' fixes #21

### LINKED ISSUE #21: Missing a non consuming but successful route
This is required in order to enable describing a root Route (`\`)

### PR DESCRIPTION
**Pull request by sledorze**

### CODE REVIEW

**Comment by gcanti** [comment]
@sledorze if it matches everything, consumes nothing  and its signature is `Match<{}>` then it looks useless by definition. 
Sorry but, as commented in the related issue, I still have no idea what's the use case for such a parser.

**Comment by sledorze** [comment]
@gcanti I've added further explanation.
Also note the similarity with `parser-ts` `succeed` combinator.

**Comment by sledorze** [comment]
@gcanti Yes totally agree! I'll make the changes over the day!

**Comment by sledorze** [comment]
@gcanti that's way better, can we merge it?

**Pull request merged**
